### ISSUE TITLE
Invalid market don't throws error

### ISSUE THREAD

**Issue by Salvatore-Giordano** [pdepip/go-binance#11]
If I check a market using a wrong format the function getlastprice get a nil error, but it should throw an error with something like "market invalid".
An example: btcltc instead of ltcbtc throws no error

**Comment by svarogg** [comment]
I think that actually no matter what invalid request you send - there's no error.

Looked at the code, it's actually not checking the result of the request - only that it returned.

Will try to fix the issue and send a PR.

**Comment by svarogg** [comment]
I have fixed this issue, but it looks like this repo is not being actively maintained.

If you want, you can try my fork: https://github.com/svarogg/go-binance/
